[package]
name = "p01_3dr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
map-gen-2d = "0.1.2"
rand = "0.8.5"
console_error_panic_hook = "0.1"
